# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bb5b0f179231a1ed31a7b74ef4e5e3c12fdfd0ffd7093d3d9a10f00baa1ce0b095d229b421d7f6283cd4cad2cc62dc60dc622b1cac54c9bdbcd2883826f927c

test:
  secret_key_base: d720502f92eaa2940e43f90b505bfe3607712c9799785c49163fbfc9b47b9f5df5ccd94b4979a7cfd547e758bd1076781cf94ca193b738552233bf200d08b85f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
